config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    #瀏覽所有餐廳的最新動態
    collection do
      get :feeds
      get :ranking
    end
  
    #瀏覽個別餐廳的 Dashboard
    member do
      get :dashboard
      post :favorite
      post :unfavorite
      post :like
      post :unlike
    end  

  end
  resources :categories, only: :show
  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]

  resources :users, only: [:index, :edit, :show, :update] do
    member do
      get :friend_list
    end
  end
  root "restaurants#index" 

  namespace :admin do
    resources :restaurants
    resources :categories   
    root "restaurants#index"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :name
  mount_uploader :avatar, AvatarUploader


  # 如果 User 已經有了評論，就不允許刪除帳號（刪除時拋出 Error）
  has_many :comments, dependent: :restrict_with_error

  has_many :restaurants, through: :comments

  # 「使用者收藏很多餐廳」的多對多關聯
  has_many :favorites, dependent: :destroy
  has_many :favorited_restaurants, through: :favorites, source: :restaurant

  has_many :likes, dependent: :destroy
  has_many :liked_restaurants, through: :likes, source: :restaurant

  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships

  has_many :inverser_followships, class_name: "Followship", foreign_key: "following_id"
  has_many :followers, through: :inverser_followships, source: :user

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  # source -> the key that needs to be returned (friend-> friend_id)
  has_many :inverser_friendships, class_name: "Friendship", foreign_key: "friend_id" 
  has_many :frienders, through: :inverser_friendships, source: :friend

  def admin?
    self.role == "admin"
  end

  #check the following status
  def following?(user)
    self.followings.include?(user)
  end

  def friend?(user)
    self.friends.include?(user)
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :friend_list]
  
  def index
    @users = User.all
  end

  def show
    @commented_restaurants = @user.restaurants.uniq
    @favorited_restaurants = @user.favorited_restaurants
    @followings = @user.followings
    @followers = @user.followers
    @friends = @user.friends
    @frienders = @user.frienders
  end

  def friend_list
    @frienders = @user.frienders
  end

  def edit
    unless @user == current_user
      redirect_to user_path(@user)
    end
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :intro, :avatar)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-6 col-md-offset-3">

      <h3>Edit Profile</h3>

      <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.label :name, "Name" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :intro, "自我介紹" %>
          <%= f.text_area :intro, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :avatar, "大頭照上傳" %>
          <%= image_tag @user.avatar.url if @user.avatar? %>
          <%= f.file_field :avatar %>
        </div>
        
        <div class="form-group">
          <%= f.submit "Update", class: "btn btn-primary" %>
          <%= link_to "Cancel", user_path(@user), class: "btn btn-default" %>
        </div>
      <% end %>

    </div>

  </div>
</div>

app/views/users/friend_list.html.erb
<div class="col-md-8">

        <div class="panel panel-default">
          <!-- 顯示已評論餐廳的清單 -->
          <div class="panel-heading">
            <h3 class="panel-title">朋友專欄(追蹤你的朋友)</h3>
          </div>

          <div class="panel-body">
            <% @user.frienders.each do |friender| %>
              
                <div class="my-restaurant">
                  <div>
                    <% if friender.avatar.url %>
                      <%= image_tag friender.avatar.url %>
                    <% else %>
                      <%= image_tag "http://via.placeholder.com/100x100", class: "img-rounded" %>
                    <% end %>
                  </div>
                  <h5><%= friender.name %></h5>
                </div>
              
            <% end %>
          </div>
        </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">

    <ul class="nav nav-tabs">
      <li role="presentation" >
        <%= link_to '首頁', root_path %>
      </li>
      <li role="presentation">
        <%= link_to '最新動態' %>
      </li>
      <li role="presentation">
        <%= link_to 'TOP10人氣餐廳', ranking_restaurants_path %>
      </li>
      <li role="presentation" class="active">
        <%= link_to '美食達人', users_path %>
      </li>
    </ul>

  </div>
</div>

<div class="container">
  <div class="row">

    <div class="col-md-12">
      <div class="page-header">
        <h1>美食達人</h1>
      </div>
    </div>

    <% @users.each do |user| %>
      <div class="col-md-3 col-sm-4 col-xs-6">

        <%= link_to user_path(user) do %>
          <% if user.avatar.url %>
            <%= image_tag user.avatar.url, height: 200, width:200, class: "img-responsive img-rounded" %>
          <% else %>
            <img src=" http://via.placeholder.com/280x280 " class="img-responsive img-rounded">
          <% end %>
        <% end %>
        <div class = "text-center user-item">
          <h4><%= user.name %></h4>
          <%= render partial: "shared/follow", locals: {user: user} %>
          <%= render partial: "shared/friend", locals: {user: user} %>
        </div>

      </div>
    <% end %>

  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">

      <!-- page-header 裡面顯示個人檔案資料 -->
      <div class="page-header">

        <div class="col-md-3 col-sm-4">
          <div class="text-center">
            <% if @user.avatar.url %>
            <%= image_tag @user.avatar.url, class: "img-responsive img-rounded" %>
            <% else %>
            <img src="http://via.placeholder.com/350x350" class="img-responsive img-rounded">
            <% end %>
          </div>
        </div>

        <div class="col-md-9 col-sm-8">
          <h2><%= @user.name %></h2>
          <p><strong><%= @user.email %></strong></p>
          <!-- inline & unstyled 的 list -->
          <ul class="list-unstyled list-inline">
            <li><strong><%= @commented_restaurants.count %></strong> 已評論餐廳</li>
            <li><strong><%= @favorited_restaurants.count %></strong> 收藏的餐廳</li>
            <li><strong><%= @followings.count %></strong> followings</li>
            <li><strong><%= @followers.count %></strong> followers</li>
          </ul>
          <div><%= simple_format @user.intro %></div>
          <% if @user.email == current_user.email %>
            <%= link_to 'Edit Profile', edit_user_path(@user), class: "btn btn-primary" %>
            <%= link_to 'Friend List', friend_list_user_path(@user), class: "btn btn-primary" %>
          <% end %>
        </div>
        <div class="clearfix"></div>
      </div>

      <br>  

      <div class="col-md-4">
        <!-- 顯示followings的清單，panel包一個list-group  -->
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><%= @followings.count %></strong> followings</h3>
          </div>

          <ul class="list-group">
            <% @followings.each do |following| %>
            <li class="list-group-item">
              <%= link_to user_path(following) do %>
              <% if following.avatar.url %>
                <%= image_tag following.avatar.url, class: "img-responsive center-block" %>
              <% else %>
                <img src="http://via.placeholder.com/30x30" class="img-responsive img-rounded">
              <% end %>
              <%= following.name %>
              <% end %>
            </li>
            <% end %>
          </ul>
        </div>

        <!-- 顯示followers的清單，panel包一個list-group  -->
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title"><%= @followers.count %></strong> followers</h3>
          </div>

          <ul class="list-group">
            <% @followers.each do |follower| %>
            <li class="list-group-item">
              <%= link_to user_path(follower) do %>
              <% if follower.avatar.url %>
                <%= image_tag follower.avatar.url, height: 30, width: 30, class: "img-circle" %>
              <% else %>
                <img src="http://via.placeholder.com/30x30" class="img-responsive img-rounded">
              <% end %>
              <%= follower.name %>
              <% end %>
            </li>
            <% end %>
          </ul>
        </div>
      </div>

      <div class="col-md-8">

        <div class="panel panel-default">
          <!-- 顯示已評論餐廳的清單 -->
          <div class="panel-heading">
            <h3 class="panel-title"><%= @commented_restaurants.count %>間已評論餐廳</h3>
          </div>

          <div class="panel-body">
            <% @commented_restaurants.each do |restaurant| %>
              <%= link_to restaurant_path(restaurant) do %>
                <div class="my-restaurant">
                  <div>
                    <% if restaurant.image.url %>
                      <%= image_tag restaurant.image.url, width: '100px', height: '100px' %>
                    <% else %>
                      <%= image_tag "http://via.placeholder.com/100x100", class: "img-rounded" %>
                    <% end %>
                  </div>
                  <h5><%= restaurant.name %></h5>
                </div>
              <% end %>
            <% end %>
          </div>

           <!-- 顯示收藏的餐廳的清單，panel包一個panel-body裡面簡單顯示餐廳圖片和name -->
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title"><strong><%= @favorited_restaurants.count %></strong> 收藏的餐廳</h3>
            </div>

            <div class="panel-body">
              <% @favorited_restaurants.each do |restaurant| %>
                <div class="my-restaurant">
                  <div>
                    <%= link_to restaurant_path(restaurant) do %>
                      <% if restaurant.image.url %>
                        <%= image_tag restaurant.image.url, width: '100px', height: '100px',class: "img-responsive img-rounded" %>
                      <% else %>
                        <%= image_tag "http://via.placeholder.com/100x100", class: "img-rounded" %>
                      <% end %>
                      <h5><%= restaurant.name %></h5>
                    <% end %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>


      

     



    </div>
  </div>
</div>