config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    #瀏覽所有餐廳的最新動態
    collection do
      get :feeds
      get :ranking
    end
  
    #瀏覽個別餐廳的 Dashboard
    member do
      get :dashboard
      post :favorite
      post :unfavorite
      post :like
      post :unlike
    end  

  end
  resources :categories, only: :show
  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]

  resources :users, only: [:index, :edit, :show, :update] do
    member do
      get :friend_list
    end
  end
  root "restaurants#index" 

  namespace :admin do
    resources :restaurants
    resources :categories   
    root "restaurants#index"
  end

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  #設定關聯
  belongs_to :category

  # 如果刪除Restaurant也會一併刪除Comment
  has_many :comments, dependent: :destroy
  mount_uploader :image, PhotoUploader
  
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  
  #確認資料有填寫
  validates_presence_of :name, :opening_hours, :tel, :address, :description

  def is_favorited?(user)
    self.favorited_users.include?(user)
  end

  def is_liked?(user)
    self.liked_users.include?(user)
  end  
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  
  def index
    @restaurants = Restaurant.page(params[:page]).per(10)
  end

  def new 
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = "restaurant was successfully created"
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "restaurant was failed to create"
      render :new
    end
  end

  def update
    if @restaurant.save
      flash[:notice] = "restaurant was successfully updated"
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "restaurant was failed to update"
      render :edit
    end

  end

  def destroy
    @restaurant.destroy
    redirect_to admin_restaurants_path
    flash[:alert] = "restaurant was deleted"
  end

  private

    def restaurant_params
      params.require(:restaurant).permit(:name, :opening_hours, :tel, :address, :description, :image, :category_id)
    end

    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :dashboard, :favorite, :unfavorite, :like, :unlike]
  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all
  end

  def show
    @comment = Comment.new
  end

  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
  end

  def ranking
    @restaurants = Restaurant.order(favorites_count: :desc).limit(10)
  end

  def dashboard
  end

  def favorite
    #create relations (user_id and restaurant_id)
    @restaurant.favorites.create!(user: current_user)
    #back to last the page with default page

    redirect_back(fallback_location: root_path)
  end

  def unfavorite
    favorite = Favorite.where(restaurant: @restaurant, user: current_user).first
    favorite.destroy

    redirect_back(fallback_location: root_path)
  end

  def like
    #create relations (user_id and restaurant_id)
    @restaurant.likes.create!(user: current_user)
    #back to last the page with default page
    redirect_back(fallback_location: root_path)
  end

  def unlike
    likes = Like.where(restaurant: @restaurant, user: current_user).first
    likes.destroy
    redirect_back(fallback_location: root_path)
  end

  private

    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/admin/restaurants/_form.html.erb
<% if @restaurant.errors.any? %>
  <h2>We have some errors here !</h2>
  <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for  [:admin, @restaurant] do |f| %>

  <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: true}, {class: "form-control"} %>

  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>

  <%= f.label :tel, "Tel" %>
  <%= f.text_field :tel %>

  <%= f.label :address, "Address" %>
  <%= f.text_field :address %>

  <%= f.label :opening_hours, "Opening Hours" %>
  <%= f.text_field :opening_hours %>

  <%= f.label :description, "Description" %>
  <%= f.text_area :description %>

  <%= f.label :image, "Photo" %>
  <%= image_tag @restaurant.image.url, width: '300px' if @restaurant.image? %>
  <%= f.file_field :image %>
    
  <%= f.submit %>
<% end %>

app/views/admin/restaurants/edit.html.erb
<%= render partial: "form"%>

app/views/admin/restaurants/index.html.erb
<div class="container">

  <h1>餐廳後台</h1>

  <div class="row">

    <div class="col-md-12">

      <div>
        <%= link_to 'New Restaurant', new_admin_restaurant_path, class: "btn btn-primary" %>
      </div>
      <br>
      <table class="table table-striped table-bordered">
        <thead>
          <div>
            <%= link_to 'Restaurant', admin_restaurants_path %> |
            <%= link_to 'Categories', admin_categories_path %>
          </div>
          <tr>
            <th>#</th>
            <th>Category</th>
            <th>Name</th>
            <th>#</th>
          </tr>
        </thead>
        <tbody>
          <% @restaurants.each do |restaurant| %>
          <tr>
            <th scope="row"><%= restaurant.id %></th>
            <th scope="row"><%= restaurant.category.name %></th>
            <td><%= restaurant.name %></td>
            <td>
              <%= link_to 'Show', admin_restaurant_path(restaurant) %>
              <%= link_to 'Edit', edit_admin_restaurant_path(restaurant) %>
              <%= link_to 'Delete', admin_restaurant_path(restaurant), method: :delete, data: { confirm: "Are you sure?"} %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <div class="text-center">
        <%= paginate @restaurants %>
      </div>

    </div>

  </div>
</div>

app/views/admin/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
  <h2>We have some errors here !</h2>
  <ul>
    <% @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for  [:admin, @restaurant] do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>

  <%= f.label :tel, "Tel" %>
  <%= f.text_field :tel %>

  <%= f.label :address, "Address" %>
  <%= f.text_field :address %>

  <%= f.label :opening_hours, "Opening Hours" %>
  <%= f.text_field :opening_hours %>

  <%= f.label :description, "Description" %>
  <%= f.text_area :description %>

  <%= f.submit %>
<% end %>

app/views/admin/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1><%= @restaurant.name %></h1>
      <%= @restaurant.category.name %>
    </div>

    <div class="col-md-4">
      <% if @restaurant.image.url %>
        <%= image_tag @restaurant.image.url, class: "img-responsive center-block" %>
      <% end %>
      <br>
      <div class="well">
        <ul class="list-unstyled">

          <li><strong>Opening Hour:</strong> <%= @restaurant.opening_hours %></li>
          <li><strong>Tel:</strong> <%= @restaurant.tel %></li>
          <li><strong>Address:</strong> <%= @restaurant.address %></li>
        </ul>
      </div>
    </div>
    <div class="col-md-8">
      <%= simple_format @restaurant.description %>
    </div>

    <div class="clearfix"></div>

    <hr>

  </div>
</div>