config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    #瀏覽所有餐廳的最新動態
    collection do
      get :feeds
      get :ranking
    end
  
    #瀏覽個別餐廳的 Dashboard
    member do
      get :dashboard
      post :favorite
      post :unfavorite
      post :like
      post :unlike
    end  

  end
  resources :categories, only: :show
  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]

  resources :users, only: [:index, :edit, :show, :update] do
    member do
      get :friend_list
    end
  end
  root "restaurants#index" 

  namespace :admin do
    resources :restaurants
    resources :categories   
    root "restaurants#index"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :name
  
  # 如果分類下已有餐廳，就不允許刪除分類（刪除時拋出 Error）
  has_many :restaurants, dependent: :restrict_with_error
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
    belongs_to :restaurant, counter_cache: true
  # counter_cache 可以自動回傳 size 方法結果，計算關聯物件的數量
  # 必須在關聯 Model 上加一個欄位，慣例命名為 {table_name}_count
  # 指南：https://rails.ruby.tw/association_basics.html
  # 打開 counter_cache 之後，也會啟動這些相關方法：http://api.rubyonrails.org/v5.0/classes/ActiveRecord/CounterCache/ClassMethods.html
  # 有了 counter_cache 之後，就不需要手工撰寫的方法了，可以回 Model 和 Controler 將之刪除
end

app/models/followship.rb
class Followship < ApplicationRecord
  validates :following_id, uniqueness: { scope: :user_id }

  belongs_to :user
  belongs_to :following, class_name: "User"
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  validates :friend_id, uniqueness: { scope: :user_id }

  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  #設定關聯
  belongs_to :category

  # 如果刪除Restaurant也會一併刪除Comment
  has_many :comments, dependent: :destroy
  mount_uploader :image, PhotoUploader
  
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  
  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :user
  
  #確認資料有填寫
  validates_presence_of :name, :opening_hours, :tel, :address, :description

  def is_favorited?(user)
    self.favorited_users.include?(user)
  end

  def is_liked?(user)
    self.liked_users.include?(user)
  end  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :name
  mount_uploader :avatar, AvatarUploader


  # 如果 User 已經有了評論，就不允許刪除帳號（刪除時拋出 Error）
  has_many :comments, dependent: :restrict_with_error

  has_many :restaurants, through: :comments

  # 「使用者收藏很多餐廳」的多對多關聯
  has_many :favorites, dependent: :destroy
  has_many :favorited_restaurants, through: :favorites, source: :restaurant

  has_many :likes, dependent: :destroy
  has_many :liked_restaurants, through: :likes, source: :restaurant

  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships

  has_many :inverser_followships, class_name: "Followship", foreign_key: "following_id"
  has_many :followers, through: :inverser_followships, source: :user

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  # source -> the key that needs to be returned (friend-> friend_id)
  has_many :inverser_friendships, class_name: "Friendship", foreign_key: "friend_id" 
  has_many :frienders, through: :inverser_friendships, source: :friend

  def admin?
    self.role == "admin"
  end

  #check the following status
  def following?(user)
    self.followings.include?(user)
  end

  def friend?(user)
    self.friends.include?(user)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  private

  def authenticate_admin
    unless current_user.admin?
      flash[:alert] = "Not allow!"
      redirect_to root_path
    end
  end

   protected

  # Devise 客製化屬性的使用說明：  https://github.com/plataformatec/devise#strong-parameters

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @restaurants = @category.restaurants.page(params[:page]).per(9)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    #find restaurant 
    @restaurant = Restaurant.find(params[:restaurant_id])
    #build relationship
    @comment = @restaurant.comments.build(comment_params)
    @comment.user = current_user
    #saver加了驚嘆號 代表如果出錯會直接丟出錯誤畫面
    @comment.save!
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = Comment.find(params[:id])

    if current_user.admin?
      @comment.destroy
      redirect_to restaurant_path(@restaurant)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :friend_list]
  
  def index
    @users = User.all
  end

  def show
    @commented_restaurants = @user.restaurants.uniq
    @favorited_restaurants = @user.favorited_restaurants
    @followings = @user.followings
    @followers = @user.followers
    @friends = @user.friends
    @frienders = @user.frienders
  end

  def friend_list
    @frienders = @user.frienders
  end

  def edit
    unless @user == current_user
      redirect_to user_path(@user)
    end
  end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end

private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :intro, :avatar)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followships_helper.rb
module FollowshipsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantForum</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <!-- 導覽列 -->
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "餐廳評論網", root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="pull-right text-right nav navbar-nav">
            <% if current_user %>
              <% if current_user.admin? %>
                <li><%= link_to 'Admin後台', admin_restaurants_path %></li>
              <% end %>
            <li><p class="navbar-text">Hi, <%= current_user.email %></p></li>
            <li><%= link_to 'Profile', user_path(current_user) %></li>
            <li><%= link_to('登出', destroy_user_session_path, method: :delete) %></li>
            <li><%= link_to('修改密碼', edit_user_registration_path) %></li>
            <% else %>
            <li><%= link_to('註冊', new_user_registration_path) %></li>
            <li><%= link_to('登入', new_user_session_path) %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    
     <% if flash[:notice] %>
    <div class="container">
      <div class="row">
        <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= notice %>
        </div>
      </div>
    </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="container">
      <div class="row">
        <div class="alert alert-danger alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <%= alert %>
        </div>
      </div>
    </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_favorite.html.erb
<% if restaurant.is_favorited?(current_user) %>
  <%= link_to 'Unfavorite', unfavorite_restaurant_path(restaurant), method: :post, class: "btn btn-info" %>
<% else %>
  <%= link_to 'Favorite', favorite_restaurant_path(restaurant), method: :post, class: "btn btn-primary" %>
<% end %>

app/views/shared/_follow.html.erb
<% if user != current_user %>
  <% if current_user.following?(user)%>
    <%= link_to 'Unfollow', followship_path(user), method: :delete, class: "btn btn-link" %>
  <% else %>
    <%= link_to 'Follow', followships_path(following_id: user), method: :post, class: "btn btn-default" %>
  <% end %>
<% end %>

app/views/shared/_friend.html.erb
<% if user != current_user %>
  <% if current_user.friend?(user)%>
    <%= link_to 'Unfriend', friendship_path(user), method: :delete, class: "btn btn-link" %>
  <% else %>
    <%= link_to 'Friend', friendships_path(friend_id: user), method: :post, class: "btn btn-default" %>
  <% end %>
<% end %>

app/views/shared/_like.html.erb
<% if restaurant.is_liked?(current_user) %>
  <%= link_to 'Unlike', unlike_restaurant_path(restaurant), method: :post, class: "btn btn-info" %>
<% else %>
  <%= link_to 'Like', like_restaurant_path(restaurant), method: :post, class: "btn btn-primary" %>
<% end %>

app/views/shared/_restaurant_list.html.erb
<!-- restaurants list，有多寫restaurant-item的class style -->
    <% @restaurants.each do |restaurant| %>
      <div class="col-sm-6 col-md-4">
        <div class="restaurant-item">
          <% if restaurant.image.url %>
            <%= image_tag restaurant.image.url, class: "img-responsive center-block" %>
          <% else %>
          <img src="http://via.placeholder.com/500x300" class="img-responsive img-rounded">
          <% end %>
          <div class="caption">
            <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
            <p class="label label-default"><%= restaurant.category.name %><p>
            <p><%= truncate(restaurant.description, length: 80) %></p>
            <!-- pass in the local variable accordingly -->
            <%= render partial: "shared/favorite", locals: {restaurant: restaurant} %>
            <%= render partial: "shared/like", locals: {restaurant: restaurant} %>
          </div>
        </div>
      </div>
    <% end %>
      
    <!-- 有generate kaminari paginate bootstrap style -->
    <div class="text-center">
      <%= paginate @restaurants %>
    </div>